/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AplikasiPenjualan;

import com.sun.jdi.connect.spi.Connection;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PemesananTxt = new javax.swing.JTextField();
        HargatanahTxt = new javax.swing.JTextField();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TipekecilR = new javax.swing.JRadioButton();
        TipesedangR = new javax.swing.JRadioButton();
        TipebesarR = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        LuasTanahTxt = new javax.swing.JTextField();
        HargaBangunanTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tersediatanah = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalprice = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        CicilanTxt = new javax.swing.JTextField();
        PPNtxt = new javax.swing.JTextField();
        CicilanbulanTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        setujucek = new javax.swing.JCheckBox();
        ProsesButton = new javax.swing.JButton();
        SimpanButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        kembali = new javax.swing.JButton();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        PemesananTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PemesananTxt.setToolTipText("");

        HargatanahTxt.setEditable(false);
        HargatanahTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HargatanahTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargatanahTxtActionPerformed(evt);
            }
        });

        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "CIPENDEUY", "PANORAMA", "PLERED", "WANAYASA" }));
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiPenjualan/perumahan.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel4.setText("Harga Bangunan");

        jLabel6.setText("Tipe Rumah");

        radioButton.add(TipekecilR);
        TipekecilR.setText("TIPE - 34");
        TipekecilR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipekecilRActionPerformed(evt);
            }
        });

        radioButton.add(TipesedangR);
        TipesedangR.setText("TIPE - 48");
        TipesedangR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipesedangRActionPerformed(evt);
            }
        });

        radioButton.add(TipebesarR);
        TipebesarR.setText("TIPE -  60");
        TipebesarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipebesarRActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Asli");

        LuasTanahTxt.setEditable(false);
        LuasTanahTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LuasTanahTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuasTanahTxtActionPerformed(evt);
            }
        });

        HargaBangunanTxt.setEditable(false);
        HargaBangunanTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Luas Tanah Tersedia");

        tersediatanah.setEditable(false);
        tersediatanah.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPN (15%)");

        jLabel13.setText("Cicilan / Bulan");

        totalprice.setEditable(false);
        totalprice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpriceActionPerformed(evt);
            }
        });

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DPTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DPTxtActionPerformed(evt);
            }
        });

        CicilanTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CicilanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CicilanTxtActionPerformed(evt);
            }
        });

        PPNtxt.setEditable(false);
        PPNtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PPNtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPNtxtActionPerformed(evt);
            }
        });

        CicilanbulanTxt.setEditable(false);
        CicilanbulanTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CicilanbulanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CicilanbulanTxtActionPerformed(evt);
            }
        });

        jLabel14.setText("Bulan");

        setujucek.setText("Setuju");
        setujucek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujucekActionPerformed(evt);
            }
        });

        ProsesButton.setText("PROSES");
        ProsesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesButtonActionPerformed(evt);
            }
        });

        SimpanButton.setText("SIMPAN");
        SimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanButtonActionPerformed(evt);
            }
        });

        HapusButton.setText("HAPUS");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        kembali.setText("Menu Utama");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(areaCombobox, 0, 167, Short.MAX_VALUE)
                                        .addComponent(PemesananTxt))
                                    .addComponent(HargatanahTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kembali)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(TipekecilR))
                    .addComponent(TipesedangR)
                    .addComponent(TipebesarR)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(ProsesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(HargaBangunanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(LuasTanahTxt)
                            .addComponent(jLabel8)
                            .addComponent(tersediatanah, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(totalprice)
                            .addComponent(DPTxt)
                            .addComponent(CicilanTxt)
                            .addComponent(PPNtxt)
                            .addComponent(CicilanbulanTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setujucek)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SimpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(HapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PemesananTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HargaBangunanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(HargatanahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipekecilR)
                            .addComponent(LuasTanahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipesedangR)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TipebesarR)
                            .addComponent(tersediatanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CicilanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(PPNtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CicilanbulanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(setujucek)))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProsesButton)
                    .addComponent(SimpanButton)
                    .addComponent(HapusButton)
                    .addComponent(kembali))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HargatanahTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargatanahTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargatanahTxtActionPerformed

    private void totalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpriceActionPerformed

    private void DPTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DPTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DPTxtActionPerformed

    private void CicilanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CicilanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CicilanTxtActionPerformed

    private void PPNtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPNtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPNtxtActionPerformed

    private void CicilanbulanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CicilanbulanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CicilanbulanTxtActionPerformed

    private void setujucekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujucekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setujucekActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
    PemesananTxt.setText("");
    HargatanahTxt.setText("");
    HargaBangunanTxt.setText("");
    LuasTanahTxt.setText("");
    tersediatanah.setText("");
    totalprice.setText("");
    DPTxt.setText("");
    CicilanTxt.setText("");
    PPNtxt.setText("");
    CicilanbulanTxt.setText("");
    areaCombobox.setSelectedIndex(0);
    radioButton.clearSelection();
    setujucek.setSelected(false);
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
    switch(areaCombobox.getSelectedIndex()){
        case 0:
            HargatanahTxt.setText("");
            HargaBangunanTxt.setText("");
            break;
        case 1:
            HargatanahTxt.setText("500000");
            HargaBangunanTxt.setText("90000000");
            break;
        case 2:
            HargatanahTxt.setText("600000");
            HargaBangunanTxt.setText("120000000");
            break;
        case 3:
            HargatanahTxt.setText("450000");
            HargaBangunanTxt.setText("70000000");
            break;
        default:
            HargatanahTxt.setText("800000");
            HargaBangunanTxt.setText("820000000");
            break;
                    
    }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void TipekecilRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipekecilRActionPerformed
  if(areaCombobox.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "Pilih Area Dahulu");
        radioButton.clearSelection();
    }else{
        LuasTanahTxt.setText("60");
        tersediatanah.setText("26");
        long landprice = Long.parseLong(HargatanahTxt.getText()),
                buildingPrice = Long.parseLong(HargaBangunanTxt.getText()),
                avaibleland = Long.parseLong(tersediatanah.getText()),
                totalharga;
            totalharga = (avaibleland * landprice) + buildingPrice ;
            totalprice.setText(""+totalharga);

            CicilanbulanTxt.setText("");
            DPTxt.setText("");
            PPNtxt.setText("");
            CicilanTxt.setText("");
    }
    }//GEN-LAST:event_TipekecilRActionPerformed

    private void TipesedangRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipesedangRActionPerformed
  if(areaCombobox.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "Pilih Area Dahulu");
        radioButton.clearSelection();
    }else{
        LuasTanahTxt.setText("90");
        tersediatanah.setText("42");
        long landprice = Long.parseLong(HargatanahTxt.getText()),
                buildingPrice = Long.parseLong(HargaBangunanTxt.getText()),
                avaibleland = Long.parseLong(tersediatanah.getText()),
                totalharga;
            totalharga = (avaibleland * landprice) + buildingPrice ;
            totalprice.setText(""+totalharga);

            CicilanbulanTxt.setText("");
            DPTxt.setText("");
            PPNtxt.setText("");
            CicilanTxt.setText("");
    }
    }//GEN-LAST:event_TipesedangRActionPerformed

    private void TipebesarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipebesarRActionPerformed
  if(areaCombobox.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null, "Pilih Area Dahulu");
        radioButton.clearSelection();
    }else{
        LuasTanahTxt.setText("120");
        tersediatanah.setText("60");
        long hargatanah = Long.parseLong(HargatanahTxt.getText()),
                hargabangunan = Long.parseLong(HargaBangunanTxt.getText()),
                tersediatanahtxt = Long.parseLong(tersediatanah.getText()),
                totalharga;
            totalharga = (tersediatanahtxt * hargatanah) + hargabangunan ;
            totalprice.setText(""+totalharga);
            
            DPTxt.setText("");
            PPNtxt.setText("");
            CicilanTxt.setText("");
    }
    }//GEN-LAST:event_TipebesarRActionPerformed

    private void ProsesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesButtonActionPerformed
    if(totalprice.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Pilihan Belum Lengkap");
    }else if(DPTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "DP harus diisi");
    }else if(CicilanTxt.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Isi jumlah cicilan yang di inginkan");
    }else{
        long hargatanah = Long.parseLong(HargatanahTxt.getText()),
                hargabangunan = Long.parseLong(HargaBangunanTxt.getText()),
                tersediatanahtxt = Long.parseLong(tersediatanah.getText()),
                dp = Long.parseLong(DPTxt.getText()),
                cicilan = Long.parseLong(CicilanTxt.getText()),
                totalharga, ppn ,Cicilanbulan;
            totalharga = (tersediatanahtxt * hargatanah) + hargabangunan;
            ppn = totalharga *15/100;
            Cicilanbulan = (totalharga +ppn)/cicilan;
            PPNtxt.setText(""+ppn);
            CicilanbulanTxt.setText(""+Cicilanbulan); 
    }//GEN-LAST:event_ProsesButtonActionPerformed
    }
    private void LuasTanahTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuasTanahTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuasTanahTxtActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
     OptionMenu optionMenu = new OptionMenu();
     optionMenu.setVisible(true);
     this.getDesktopPane().add(optionMenu);
     this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void SimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanButtonActionPerformed
        if(setujucek.isSelected()==false){
            JOptionPane.showMessageDialog(null,
                    "Klik checkbox untuk menyetujui", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            String typeRumah;
            if(TipekecilR.isSelected()){
                typeRumah="tipe - 34";
            }else if(TipesedangR.isSelected()){
                typeRumah="tipe - 48";
            }else{
                typeRumah="tipe - 60";
            }
        
        try{
            String sql="insert into rumah values('"
                    +PemesananTxt.getText()+"','"
                    +areaCombobox.getSelectedItem()+"','"
                    +typeRumah+"','"
                    +LuasTanahTxt.getText()+"','"
                    +totalprice.getText()+"','"
                    +DPTxt.getText()+"','"
                    +CicilanTxt.getText()+"','"
                    +CicilanbulanTxt.getText()+"')";
                 java.sql.Connection conn=(java.sql.Connection)koneksi.koneksiDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
        }
        catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
        }
      /*  try {
            String sql = "INSERT INTO rumah (name,area,tipe,luas,harga,jumlah_cicilan,cicilan_bulan)VALUES('"
                    + PemesananTxt.getText()+"','"
                    + areaCombobox.getSelectedItem()+"','"
                    
                    + LuasTanahTxt.getText()+"','"
                    + totalprice.getText()+"','"
                    + DPTxt.getText()+"','"
                    + CicilanTxt.getText()+"','";
            Connection conn=(Connection)koneksi.koneksiDB();
            PreparedStatement pst = (PreparedStatement)conn.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
          */  
            
    }//GEN-LAST:event_SimpanButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CicilanTxt;
    private javax.swing.JTextField CicilanbulanTxt;
    private javax.swing.JTextField DPTxt;
    private javax.swing.JButton HapusButton;
    private javax.swing.JTextField HargaBangunanTxt;
    private javax.swing.JTextField HargatanahTxt;
    private javax.swing.JTextField LuasTanahTxt;
    private javax.swing.JTextField PPNtxt;
    private javax.swing.JTextField PemesananTxt;
    private javax.swing.JButton ProsesButton;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JRadioButton TipebesarR;
    private javax.swing.JRadioButton TipekecilR;
    private javax.swing.JRadioButton TipesedangR;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kembali;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JCheckBox setujucek;
    private javax.swing.JTextField tersediatanah;
    private javax.swing.JTextField totalprice;
    // End of variables declaration//GEN-END:variables
}
